workspace:
  base: /test
  path: oe_authorisation

services:
  web:
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    environment:
    - DOCUMENT_ROOT=/test/oe_authorisation
  mysql:
    image: percona/percona-server:5.6
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=syncope
    - MYSQL_USER=syncope
    - MYSQL_PASSWORD=syncope
  syncope:
    depends_on:
    - mysql
    image: apache/syncope:2.1.1
    restart: always
    environment:
      DBMS: "mysql"
      DB_URL: "jdbc:mysql://mysql:3306/syncope?characterEncoding=UTF-8&relaxAutoCommit=true&useSSL=false"
      DB_USER: "syncope"
      DB_PASSWORD: "syncope"
      DB_POOL_MAX: "10"
      DB_POOL_MIN: "2"
      OPENJPA_REMOTE_COMMIT: sjvm

pipeline:
  composer-install:
    group: prepare
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    volumes:
    - /cache:/cache
    commands:
    - composer install --ansi --no-suggest --no-progress

  syncope-provisioning:
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    commands:
    - ./vendor/bin/run oe-authorisation-service:setup
    - ./vendor/bin/run oe-authorisation-service:site-setup --site_id=sitea

  site-install:
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    commands:
    - ./vendor/bin/run drupal:site-install

  grumphp:
    group: test
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    commands:
    - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    commands:
    - ./vendor/bin/phpunit

  behat:
    group: test
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    commands:
    - ./vendor/bin/behat --strict

matrix:
  PHP_VERSION:
    - 7.1
    - 7.2