<?php

/**
 * @file
 * The OpenEuropa Authorisation Syncope module.
 */

declare(strict_types = 1);

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Form\FormStateInterface;
use Drupal\oe_authorisation_syncope\Exception\SyncopeUserException;
use Drupal\user\RoleInterface;
use Drupal\user\UserInterface;

/**
 * Implements hook_entity_presave().
 */
function oe_authorisation_syncope_entity_presave(EntityInterface $entity) {
  if ($entity instanceof RoleInterface) {
    \Drupal::service('oe_authorisation_syncope.role_mapper')->preSave($entity);
    return;
  }

  if ($entity instanceof UserInterface) {
    \Drupal::service('oe_authorisation_syncope.user_mapper')->preSave($entity);
    return;
  }
}

/**
 * Implements hook_entity_predelete().
 */
function oe_authorisation_syncope_entity_predelete(EntityInterface $entity) {
  if ($entity instanceof RoleInterface) {
    \Drupal::service('oe_authorisation_syncope.role_mapper')->preDelete($entity);
    return;
  }

  if ($entity instanceof UserInterface) {
    \Drupal::service('oe_authorisation_syncope.user_mapper')->preDelete($entity);
    return;
  }
}

/**
 * Implements hook_user_login().
 */
function oe_authorisation_syncope_user_login($account) {
  \Drupal::service('oe_authorisation_syncope.user_mapper')->login($account);
}

/**
 * Implements hook_ENTITY_TYPE_storage_load() for the User entity type.
 */
function oe_authorisation_syncope_user_storage_load(array $entities) {
  foreach ($entities as $entity) {
    \Drupal::service('oe_authorisation_syncope.user_mapper')->load($entity);
  }
}

/**
 * Implements hook_entity_base_field_info().
 */
function oe_authorisation_syncope_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() !== 'user') {
    return NULL;
  }

  $fields = [];

  $fields['syncope_uuid'] = BaseFieldDefinition::create('string')
    ->setLabel(t('Syncope UUID'))
    ->setDescription(t('The UUID of this User in Syncope.'));

  $fields['syncope_updated'] = BaseFieldDefinition::create('timestamp')
    ->setLabel(t('Syncope Updated'))
    ->setDescription(t('The last updated timestamp of the user in Syncope.'));

  return $fields;
}

/**
 * Implements hook_form_FORM_ID_alter() for the Account form.
 *
 * When someone wants to change the roles of a user, we need to ensure we have
 * an up-to-date status of the roles as they are in Syncope.
 */
function oe_authorisation_syncope_form_user_form_alter(&$form, FormStateInterface $form_state): void {
  /** @var \Drupal\user\ProfileForm $profile_form */
  $profile_form = $form_state->getBuildInfo()['callback_object'];
  /** @var \Drupal\user\UserInterface $user */
  $user = $profile_form->getEntity();

  $uuid = $user->get('syncope_uuid')->value;
  if (!$uuid) {
    return;
  }

  // Instead of simply resetting the cache and reloading the user, we make a
  // new call to Syncope so that we know if something goes wrong with the
  // request. If it does, we don't allow changes to this form.
  /** @var \Drupal\oe_authorisation_syncope\SyncopeRoleMapper $role_mapper */
  $role_mapper = \Drupal::service('oe_authorisation_syncope.role_mapper');

  try {
    $roles = $role_mapper->getUserDrupalRolesFromSyncope($user);
    $form['account']['roles']['#default_value'] = $roles;
  }
  catch (SyncopeUserException $e) {
    \Drupal::messenger()->addError('There is a problem with the authorisation service. User roles cannot be updated.');
    $form['account']['roles']['#disabled'] = TRUE;
  }
}
