<?php

/**
 * @file
 * OpenEuropa Syncope Authorisation install file.
 */

declare(strict_types = 1);

/**
 * Implements hook_install().
 */
function oe_authorisation_syncope_install() {
  $roles = \Drupal::entityTypeManager()->getStorage('user_role')->loadMultiple();
  $excluded = [
    'authenticated',
    'anonymous',
  ];

  foreach ($roles as $role) {
    if (in_array($role->id(), $excluded)) {
      continue;
    }

    $role->save();
  }
}
