oe_authorisation_syncope.settings:
  type: config_object
  label: 'OpenEuropa Authorisation Syncope settings'
  mapping:
    credentials:
      type: mapping
      label: 'The Syncope credentials'
      mapping:
        username:
          type: string
          label: 'The username'
        password:
          type: string
          label: 'The password'
    endpoint:
      type: string
      label: 'The Syncope endpoint'
    site_realm_name:
      type: string
      label: 'The site realm in Syncope'
    site_realm_uuid:
      type: string
      label: 'The UUID of the site realm in Syncope'
    root_realm_uuid:
      type: string
      label: 'The UUID of the root realm in Syncope'
    domain:
      type: string
      label: 'The Syncope domain'

user.role.*.third_party.oe_authorisation_syncope:
  type: mapping
  label: 'OpenEuropa Authorisation Syncope module settings on the Role entities'
  mapping:
    syncope_group:
      type: string
      label: 'The UUID of the Syncope Group that maps to this Role'
