oe_authorisation_syncope.settings:
  type: config_object
  label: 'OpenEuropa Authorisation Syncope settings'
  mapping:
    credentials:
      type: mapping
      label: 'The Syncope credentials'
      mapping:
        username:
          type: string
          label: 'The username'
        password:
          type: string
          label: 'The password'
    endpoint:
      type: string
      label: 'The Syncope endpoint'
    site_realm_name:
      type: string
      label: 'The site realm in Syncope'
    domain:
      type: string
      label: 'The Syncope domain'